# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"generate_db": "00_core.ipynb",
         "insert_row": "00_core.ipynb",
         "insert_rows": "00_core.ipynb",
         "utc_now": "00_core.ipynb",
         "readable_df": "00_core.ipynb",
         "Prodb": "00_core.ipynb",
         "get_json_from_query": "03_examples.ipynb",
         "get_current_weather": "03_examples.ipynb",
         "df_from_loc": "03_examples.ipynb",
         "visit_city": "03_examples.ipynb"}

modules = ["core.py",
           "examples.py"]

doc_url = "https://lukexyz.github.io/prodb/"

git_url = "https://github.com/lukexyz/prodb/tree/master/"

def custom_doc_links(name): return None
